### ISSUE TITLE
Wer schreibt eigentlich die User Stories?

### ISSUE THREAD

**Issue by steffbygithub** [build-a-quiz/BAQ#3]
Seht ihr das im Team genauso, wie diese Autoren?
[https://www.teamprove.de/wissen/94/wer-schreibt-eigentlich-die-user-stories](url)

**Comment by rassil0n** [comment]
Wir sehen das im Team so, dass die User-Stories beim Product-Owner bleiben sollen.
So kann auch am besten sichergestellt werden, dass die Vorstellungen des Product-Owner bestmöglich realisiert werden können.

**Comment by steffbygithub** [comment]
Ich sehe es so wie besprochen, Der P.O. ist verantwortlich für die Elstellung, Pflege, die Verfeinerung kommt vom Team.
